### ISSUE TITLE
IPFS images not showing on teh Front end

### ISSUE THREAD

**Issue by ZhectorSM** [ZhectorSM/web3-wheels-app#35]
There is an issue with the IPFS images not showing on the front end.

https://ipfs.io/ipfs/QmQnLGyE9ZiMe2ZPqZNbD7AZ1PH3YqqHADVc6LTVR3XSXf

https://ipfs.io/ipfs/QmSuwLBbmbNqi2Tpig5DzTtzFxpbcFV4yBwbbnX1nnTw5N

**Comment by 0xmihirsahu** [comment]
#36
